### ISSUE TITLE
Add a "ok, now what?" doc section

### ISSUE THREAD

**Issue by danecreekphotography** [dbuchwald/6502#2]
Update the readme.md (or some other doc) with instructions on what to do after all the parts are soldered onto the board to verify things work correctly. Include things like:

1. How to attach the clock to the main board
2. How to use a jumper on the main board to get 1MHz clock
3. Which program to run first (04_blink_s) and second (13_4bit_lcd?)

**Comment by dbuchwald** [comment]
This should be now available - can you verify and update the issue accordingly?

**Comment by danecreekphotography** [comment]
Yes, this is fixed now!
