### ISSUE TITLE
Incorrect value for  RV1 in BOM for clock module

### ISSUE THREAD

**Issue by Dave-TR3A** [dbuchwald/6502#34]
The BOM for the clock module lists a value of 10K for RV1 (a Piher PT10-LV10-105 potentiometer).
 
![image](https://user-images.githubusercontent.com/63303608/78702759-1858dc80-78d7-11ea-9423-db23fe73fe8f.png)

That must be a typo: the Piher part number is actually for a 1M potentiometer.

With a 10K pot, the astable circuit generates a square wave with frequency between 62 and 481 Hz, which may be too fast for troubleshooting. Changing to a 1M pot yields a frequency range of 0.72 to 481 Hz.

**Comment by dbuchwald** [comment]
Thanks for spotting it! I have just corrected it, can you check and let me know if it can be closed?

**Comment by Dave-TR3A** [comment]
Hi Dawid:



I just looked on GitHub. Unfortunately, I’m not seeing the change you made.



Here is a screen shot from moments ago. It shows that RV1 on the BOM is
unchanged, and also shows the URL, date and time.

By the way, I changed the 10K potentiometer on the clock for a 1 M
potentiometer. Now I’m able to generate square waves with frequencies
ranging from .67Hz to 472 Hz (as measured on my oscilloscope). That’s just
what I was hoping for.



Nice job on the clock PCB!



Stay healthy.



Best wishes,



Dave MacKay



*From:* Dawid Buchwald <notifications@github.com>
*Sent:* April 8, 2020 3:25 AM
*To:* dbuchwald/6502 <6502@noreply.github.com>
*Cc:* Dave MacKay <dave@mdmackay.ca>; Author <author@noreply.github.com>
*Subject:* Re: [dbuchwald/6502] Incorrect value for RV1 in BOM for clock
module (#34)



Thanks for spotting it! I have just corrected it, can you check and let me
know if it can be closed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dbuchwald/6502/issues/34#issuecomment-610796642>, or
unsubscribe

**Comment by Dave-TR3A** [comment]
And now the change is showing up. Here’s a screenshot showing it:



Well done! Issue closed.



*From:* Dawid Buchwald <notifications@github.com>
*Sent:* April 8, 2020 3:25 AM
*To:* dbuchwald/6502 <6502@noreply.github.com>
*Cc:* Dave MacKay <dave@mdmackay.ca>; Author <author@noreply.github.com>
*Subject:* Re: [dbuchwald/6502] Incorrect value for RV1 in BOM for clock
module (#34)



Thanks for spotting it! I have just corrected it, can you check and let me
know if it can be closed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dbuchwald/6502/issues/34#issuecomment-610796642>, or
unsubscribe

**Comment by Dave-TR3A** [comment]
Clock module BOM updated to show value of RV1 as 1M ohm.

**Comment by dbuchwald** [comment]
Thanks a lot, stay safe!
